"""
dynamics.py
===========
Dynamical system evolution for:

    A Formal Framework for Layered Asset Claims and Resolution Outcomes
    in Rehypothecation Networks
    Blessing Honmane, 2026

This script reads the synthetic network generated by network_generator.py
and runs the T-step co-evolution of:
    - Economic sub-vectors c_i^econ(t)
    - Interaction kernel G_econ(t)
    - Pairwise chain correlation rho_ij(t)
    - Margin stress mu(t)
    - Legal scaffold G_legal (stable or shocked)

It implements the simulation-specific definitions of F and G_econ entries
that are left as open problems in the paper.

Paper references
----------------
Coupled Evolution    : Section 3.8
Crisis Fixed Point   : Section 3.5
Interaction Kernel   : Definition 3.8
Collateral Shock     : Definition 5.4 (shock operator)
Simulation-specific F: companion paper specification
"""

import numpy as np
import json
import os
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from numpy.linalg import norm, cond

# -----------------------------------------------------------------------
# Parameters — must match network_generator.py
# -----------------------------------------------------------------------

RNG_SEED  = 42
rng       = np.random.default_rng(RNG_SEED + 1)   # offset so dynamics
                                                    # noise differs from init

ALPHA          = 0.002    # coupling strength in F — kept low to prevent
                          # premature saturation of econ vectors at [0,1] boundary
DELTA_T        = 1.0      # timestep size

# Collateral shock injection
SHOCK_TIMESTEP  = 35      # when the asset valuation shock hits
SHOCK_ASSET_ID  = 0       # which asset is shocked
SHOCK_MAGNITUDE = 0.25    # delta_A: fractional value loss (0.25 = 25% loss)

# Noise level on economic dimensions per timestep
ECON_NOISE_LEVEL = 0.005


# -----------------------------------------------------------------------
# Load network data
# -----------------------------------------------------------------------

def load_network(scenario_dir: str) -> dict:
    """Load all network data for one scenario."""

    data = {}

    # NumPy arrays
    data["G_econ"]        = np.load(os.path.join(scenario_dir, "G_econ_init.npy"))
    data["G_legal"]       = np.load(os.path.join(scenario_dir, "G_legal_mask_init.npy"))
    data["rho_matrix"]    = np.load(os.path.join(scenario_dir, "rho_matrix_init.npy"))
    data["econ_vectors"]  = np.load(os.path.join(scenario_dir, "econ_vectors_init.npy"))
    data["claim_vectors"] = np.load(os.path.join(scenario_dir, "claim_vectors_init.npy"))
    data["nominal"]       = np.load(os.path.join(scenario_dir, "nominal_amounts.npy"))
    data["V_A"]           = np.load(os.path.join(scenario_dir, "V_A.npy"))
    data["asset_map"]     = np.load(os.path.join(scenario_dir, "claim_asset_map.npy"))

    # JSON metadata
    with open(os.path.join(scenario_dir, "network_metadata.json")) as f:
        data["meta"] = json.load(f)

    data["scenario_config"] = data["meta"]["params"]["scenario_config"]
    data["n_claims"]        = data["meta"]["n_claims"]

    return data


# -----------------------------------------------------------------------
# Simulation-specific definition of F
# -----------------------------------------------------------------------

def apply_F(
    econ_vectors: np.ndarray,
    G_econ: np.ndarray,
    noise_level: float,
    rho_matrix: np.ndarray = None,
) -> np.ndarray:
    """
    Simulation-specific evolution function F.

    Paper: open problem — F is undefined in the theory paper.

    Key fix over the naive implementation: drift is CLAIM-SPECIFIC.
    Each claim i drifts at a rate proportional to its own mean ancestry
    overlap with other claims: rho_i = mean_j(rho_ij).

    High-connectivity claims (many shared ancestors) drift faster.
    Low-connectivity claims drift slower.
    This creates genuine differential evolution — the spread of econ
    vectors across claims changes over time rather than all claims
    moving in lockstep toward the same boundary.

    Specifically:

        c_i^econ(t+1) = c_i^econ(t)
                      + ALPHA * rho_i * G_block_i * c_i^econ(t) * DELTA_T
                      + noise_i(t)

    where rho_i = mean_j(rho_ij) is the connectivity weight of claim i,
    and G_block_i is the 3x3 diagonal block of G_econ for claim i.

    The differential rate means:
    - Encumbrance (e) grows faster for high-ancestry claims
    - Custody possession (p) degrades faster for high-ancestry claims
    - Liquidity (l) degrades faster for high-ancestry claims

    This gives the correct qualitative behaviour:
    - High-reuse claims saturate early -> their pi scores drop first
    - Low-reuse claims remain healthy longer -> their pi scores stay higher
    - The SPREAD of pi scores across claims grows with drift
    - Delta (inverse pi spread) rises monotonically with economic drift

    Paper: Section 3.8 coupled evolution, Remark 3.1 on F.
    """
    n = econ_vectors.shape[0]
    C_new = econ_vectors.copy()

    if rho_matrix is not None:
        # Per-claim connectivity: mean rho with all other claims
        rho_i = rho_matrix.mean(axis=1)   # (n,)  in [0,1]
    else:
        rho_i = np.ones(n) * 0.5

    for i in range(n):
        # 3x3 diagonal block for claim i in the 3n x 3n G_econ
        block = G_econ[3*i:3*i+3, 3*i:3*i+3]

        # Claim-specific coupling rate
        rate_i = float(rho_i[i])

        # Economic dimensions evolve at claim-specific rate
        delta_i = ALPHA * rate_i * block @ econ_vectors[i] * DELTA_T
        noise_i = rng.normal(0, noise_level, size=3)

        C_new[i] = econ_vectors[i] + delta_i + noise_i

    # Also apply cross-claim coupling at reduced weight
    # This preserves the network effect but prevents lockstep saturation
    C_flat = econ_vectors.flatten()
    cross_delta = ALPHA * 0.1 * G_econ @ C_flat * DELTA_T
    C_new += cross_delta.reshape(n, 3)

    return np.clip(C_new, 0.0, 1.0)


# -----------------------------------------------------------------------
# Update G_econ from current rho_matrix and mu
# -----------------------------------------------------------------------

def update_G_econ(
    rho_matrix: np.ndarray,
    G_legal: np.ndarray,
    mu: float
) -> np.ndarray:
    """
    Recompute G_econ from current rho_matrix and mu.

    Simulation-specific form:
        G_econ_ij(t) = rho_ij(t) * mu(t)   (conditioned on G_legal)

    The 3x3 block structure encodes cross-dimension coupling.
    Paper: Definition 3.8, simulation proxy.
    """
    n = rho_matrix.shape[0]
    G = np.zeros((3 * n, 3 * n))

    for i in range(n):
        for j in range(n):
            # Economic coupling driven by ancestry overlap only.
            # G_legal is NOT applied here -- see paper Remark on
            # Conditioning Notation and Economic Coupling.
            coupling = rho_matrix[i, j] * np.log1p(mu) / np.log1p(1.0)
            coupling = np.clip(coupling, 0, 0.3)   # hard cap prevents saturation
            if coupling < 1e-10:
                continue
            block = np.array([
                [coupling,       coupling*0.3,  coupling*0.2],
                [coupling*0.3,   coupling,      coupling*0.4],
                [coupling*0.2,   coupling*0.4,  coupling    ]
            ])
            G[3*i:3*i+3, 3*j:3*j+3] = block

    return G


# -----------------------------------------------------------------------
# Update rho_matrix as provenance paths evolve
# -----------------------------------------------------------------------

def update_rho_matrix(
    rho_matrix: np.ndarray,
    econ_vectors: np.ndarray,
    mu: float
) -> np.ndarray:
    """
    Update pairwise chain correlation rho_ij(t).

    In the full simulation, rho_ij would be recomputed from updated
    provenance paths as rehypothecation events occur. Here we use a
    simplified dynamic: rho grows slowly as mu increases, reflecting
    that higher margin stress leads to more collateral reuse which
    increases ancestry overlap.

    rho_ij(t+1) = rho_ij(t) + growth_rate * mu(t) * (1 - rho_ij(t))

    This is bounded in [0,1] by construction and converges toward 1
    as stress accumulates — correctly capturing the paper's claim that
    rising collateral reuse intensifies correlation.
    """
    growth_rate = 0.01
    delta = growth_rate * mu * (1.0 - rho_matrix)
    rho_new = rho_matrix + delta
    np.fill_diagonal(rho_new, 1.0)   # self-correlation always 1
    return np.clip(rho_new, 0.0, 1.0)


# -----------------------------------------------------------------------
# Apply legal regime shock to G_legal
# -----------------------------------------------------------------------

def apply_legal_shock(
    G_legal: np.ndarray,
    shock_magnitude: float,
    claimant_jurisdictions: np.ndarray = None
) -> np.ndarray:
    """
    Apply a discrete legal regime shock to G_legal.

    At t = LEGAL_SHOCK_TIMESTEP, a fraction shock_magnitude of
    CROSS-JURISDICTION admissible interactions become inadmissible.
    Same-jurisdiction pairs are never affected by the shock.

    This models a regulatory change, sanctions event, or jurisdiction
    exit that instantly restructures the legal scaffold.

    Paper: G_legal changes only at discrete regime-change events;
    only cross-jurisdiction pairs are affected.
    """
    G_new = G_legal.copy()
    n = G_legal.shape[0]

    for i in range(n):
        for j in range(i+1, n):
            if not G_legal[i, j]:
                continue
            # Only affect cross-jurisdiction pairs
            if claimant_jurisdictions is not None:
                if claimant_jurisdictions[i] == claimant_jurisdictions[j]:
                    continue   # same jurisdiction — unaffected by shock
            if rng.random() < shock_magnitude:
                G_new[i, j] = False
                G_new[j, i] = False

    return G_new


# -----------------------------------------------------------------------
# Apply collateral shock to economic sub-vectors
# -----------------------------------------------------------------------

def apply_collateral_shock(
    econ_vectors: np.ndarray,
    asset_map: np.ndarray,
    shock_asset_id: int,
    delta_A: float
) -> np.ndarray:
    """
    Apply collateral shock operator from paper Definition 5.4.

    For claims on the shocked asset:
        Delta c_i^econ(t) = -delta_A * rho_iA * c_i^econ(t)

    rho_iA = 1 for direct claims on the shocked asset.
    rho_iA = 0 for claims on other assets.

    This propagates the shock only through the economic sub-vector
    (p, e, l). The legal sub-vector (s, j, tau) is unaffected.
    Paper: Remark after Definition 5.4.
    """
    C_new = econ_vectors.copy()
    for i, asset_id in enumerate(asset_map):
        if asset_id == shock_asset_id:
            rho_iA = 1.0   # direct claim on shocked asset
            C_new[i] = C_new[i] * (1.0 - delta_A * rho_iA)
    return np.clip(C_new, 0.0, 1.0)


# -----------------------------------------------------------------------
# Compute condition number of G_econ
# -----------------------------------------------------------------------

def compute_kappa(G_econ: np.ndarray) -> float:
    """
    Condition number kappa(G_econ).
    Measures geometric instability of the claim space.
    Paper: Fragility Observable definition.

    Returns the true computed value clipped at 1e8 only for numerical
    stability in downstream products (e.g. beta computation).
    Use compute_kappa_raw() for summary reporting so diagnostics do not
    show the sentinel value 1e8 for all scenarios indistinguishably.
    """
    try:
        k = cond(G_econ, p=2)
        return float(np.clip(k, 1.0, 1e8))
    except Exception:
        return 1.0


def compute_kappa_raw(G_econ: np.ndarray) -> float:
    """
    True condition number without ceiling clip.
    Used for summary reporting (Fig. 9) so the table shows real peak
    values rather than the sentinel 1e8 that would falsely imply equal
    kernel instability across all crisis scenarios.
    Paper: Remark 6.5 — kappa is ill-conditioned for dense near-uniform
    matrices; the Frobenius norm is used in Phi instead. This raw value
    is for diagnostics only and should be labelled as such in the paper.
    """
    try:
        k = cond(G_econ, p=2)
        if np.isinf(k) or np.isnan(k):
            return float("inf")
        return float(k)
    except Exception:
        return float("inf")


# -----------------------------------------------------------------------
# Compute overclaim ratio L(t)
# -----------------------------------------------------------------------

def compute_L(nominal: np.ndarray, V_A: np.ndarray, asset_map: np.ndarray) -> float:
    """
    L(t) = sum(w_i) / V_A averaged across assets.
    Paper: Fragility Observable definition.
    """
    total_claims = 0.0
    total_value  = 0.0
    for a_id, V in enumerate(V_A):
        claims_on_a = nominal[asset_map == a_id]
        total_claims += claims_on_a.sum()
        total_value  += V
    return float(total_claims / total_value) if total_value > 0 else 0.0


# -----------------------------------------------------------------------
# Compute dG/dt norm
# -----------------------------------------------------------------------

def compute_dG_norm(G_current: np.ndarray, G_prev: np.ndarray) -> float:
    """
    ||dG_econ/dt|| approximated as Frobenius norm of (G_current - G_prev).
    Paper: Fragility Observable definition — rate of kernel change.
    """
    return float(norm(G_current - G_prev, ord='fro'))


# -----------------------------------------------------------------------
# Compute Phi(A,t) — fragility observable
# -----------------------------------------------------------------------

def compute_Phi(kappa: float, L: float, dG_norm: float, G_econ: np.ndarray = None) -> float:
    """
    Fragility observable Phi(A,t).

    Uses ||G_econ||_F * L * (1 + ||dG/dt||) so the signal grows
    monotonically as coupling density increases with rho and mu.
    kappa is ill-conditioned for dense near-uniform matrices.

    Paper: Definition -- Fragility Observable, Remark on limitation.
    """
    if G_econ is not None:
        G_norm = float(np.linalg.norm(G_econ, ord='fro'))
    else:
        G_norm = float(np.log1p(kappa))
    return G_norm * L * (1.0 + dG_norm)


# -----------------------------------------------------------------------
# Main dynamics loop
# -----------------------------------------------------------------------

def run_dynamics(scenario_dir: str, output_dir: str) -> dict:
    """
    Run the full T-step dynamical evolution for one scenario.

    Returns a dictionary of time series for all state variables.
    These are consumed by monitoring.py and resolution.py.
    """

    data   = load_network(scenario_dir)
    cfg    = data["scenario_config"]
    T      = cfg["T_steps"]
    n      = data["n_claims"]
    scenario = cfg["scenario"]

    print(f"\n{'='*60}")
    print(f"Running dynamics: {scenario}")
    print(f"  T={T} steps, n={n} claims")
    print(f"  {cfg.get('description','')}")
    print(f"{'='*60}")

    # --- Initialise state ---
    C_econ    = data["econ_vectors"].copy()      # (n, 3)
    G_econ    = data["G_econ"].copy()            # (3n, 3n)
    G_legal   = data["G_legal"].copy()           # (n, n)
    rho_mat   = data["rho_matrix"].copy()        # (n, n)
    nominal   = data["nominal"].copy()           # (n,)
    V_A       = data["V_A"].copy()               # (n_assets,)
    asset_map = data["asset_map"].copy()         # (n,)
    mu        = cfg["mu_initial"]

    # --- Time series storage ---
    ts_kappa    = np.zeros(T)
    ts_L        = np.zeros(T)
    ts_dG       = np.zeros(T)
    ts_Phi      = np.zeros(T)
    ts_mu       = np.zeros(T)
    ts_rho      = np.zeros(T)
    ts_G_econ   = []                             # store full G_econ each step
    ts_C_econ   = []                             # store full C_econ each step
    ts_G_legal  = []                             # store G_legal each step
    legal_shock_applied = False

    G_prev = G_econ.copy()

    for t in range(T):

        # --- 1. Apply legal regime shock if scheduled ---
        if (cfg.get("legal_shock_timestep") is not None
                and t == cfg["legal_shock_timestep"]
                and not legal_shock_applied):
            print(f"  [t={t:3d}] Legal regime shock applied "
                  f"(magnitude={cfg['legal_shock_magnitude']:.1%})")
            # Load claimant jurisdiction array so shock only affects
            # cross-jurisdiction pairs (paper: same-jurisdiction pairs unaffected)
            import json as _json
            _meta = _json.load(open(os.path.join(scenario_dir, "network_metadata.json")))
            _jur_map  = {int(k): v for k,v in _meta["jurisdiction_map"].items()}
            _claims   = _meta["claims"]
            _cl_jur   = np.array([
                _jur_map[c["holder_institution_id"]] for c in _claims
            ])
            G_legal = apply_legal_shock(G_legal, cfg["legal_shock_magnitude"], _cl_jur)
            legal_shock_applied = True

        # --- 2. Apply collateral shock if scheduled ---
        if t == SHOCK_TIMESTEP:
            print(f"  [t={t:3d}] Collateral shock on asset {SHOCK_ASSET_ID} "
                  f"(delta_A={SHOCK_MAGNITUDE:.1%})")
            C_econ = apply_collateral_shock(
                C_econ, asset_map, SHOCK_ASSET_ID, SHOCK_MAGNITUDE
            )
            # Also impair nominal amounts on shocked asset
            # This makes L(t) dynamic — paper: conservation constraint
            for i, a_id in enumerate(asset_map):
                if a_id == SHOCK_ASSET_ID:
                    nominal[i] *= (1.0 - SHOCK_MAGNITUDE * 0.5)

        # --- 2b. Gradual nominal erosion from encumbrance build-up ---
        # As encumbrance e_i rises, effective claim value erodes slightly
        # This makes L(t) vary continuously not just at shock events
        encumbrance_mean = C_econ[:, 1].mean()
        nominal_erosion  = 0.001 * encumbrance_mean
        nominal = nominal * (1.0 - nominal_erosion)
        nominal = np.maximum(nominal, 0.01)

        # --- 3. Update mu (economic drift) ---
        mu += cfg.get("economic_drift_rate", 0.0) * DELTA_T
        mu  = float(np.clip(mu, 0.0, 1.0))

        # --- 4. Update rho_matrix ---
        rho_mat = update_rho_matrix(rho_mat, C_econ, mu)

        # --- 5. Update G_econ ---
        G_prev  = G_econ.copy()
        G_econ  = update_G_econ(rho_mat, G_legal, mu)

        # --- 6. Evolve economic sub-vectors via F ---
        C_econ = apply_F(C_econ, G_econ, ECON_NOISE_LEVEL, rho_mat)

        # --- 7. Record time series ---
        kappa         = compute_kappa(G_econ)        # clipped at 1e8 for stability
        kappa_raw_t   = compute_kappa_raw(G_econ)    # true value for diagnostics
        L             = compute_L(nominal, V_A, asset_map)
        dG_norm       = compute_dG_norm(G_econ, G_prev)
        rho_scalar    = float(np.mean(rho_mat[np.triu_indices(n, k=1)]))
        Phi           = compute_Phi(kappa, L, dG_norm, G_econ)

        ts_kappa[t]   = kappa_raw_t   # store real value; Phi uses Frobenius norm internally
        ts_L[t]       = L
        ts_dG[t]      = dG_norm
        ts_Phi[t]     = Phi
        ts_mu[t]      = mu
        ts_rho[t]     = rho_scalar
        ts_G_econ.append(G_econ.copy())
        ts_C_econ.append(C_econ.copy())
        ts_G_legal.append(G_legal.copy())

    print(f"\n  Final state at t={T-1}:")
    print(f"    mu       = {ts_mu[-1]:.4f}")
    print(f"    rho(T)   = {ts_rho[-1]:.4f}")
    print(f"    kappa    = {ts_kappa[-1]:.2f}")
    print(f"    L        = {ts_L[-1]:.4f}")
    print(f"    dG_norm  = {ts_dG[-1]:.6f}")
    print(f"    Phi      = {ts_Phi[-1]:.4f}")

    results = {
        "scenario":    scenario,
        "T":           T,
        "n_claims":    n,
        "ts_kappa":    ts_kappa,
        "ts_L":        ts_L,
        "ts_dG":       ts_dG,
        "ts_Phi":      ts_Phi,
        "ts_mu":       ts_mu,
        "ts_rho":      ts_rho,
        "ts_G_econ":   ts_G_econ,
        "ts_C_econ":   ts_C_econ,
        "ts_G_legal":  ts_G_legal,
        "G_legal_final": G_legal,
        "nominal":     nominal,
        "V_A":         V_A,
        "asset_map":   asset_map,
        "meta":        data["meta"],
        "cfg":         cfg,
        "shock_timestep":  SHOCK_TIMESTEP,
        "shock_asset_id":  SHOCK_ASSET_ID,
        "shock_magnitude": SHOCK_MAGNITUDE,
    }

    return results


# -----------------------------------------------------------------------
# Save dynamics output
# -----------------------------------------------------------------------

def save_dynamics(results: dict, output_dir: str) -> None:
    """Save all time series arrays for consumption by monitoring.py."""
    os.makedirs(output_dir, exist_ok=True)

    np.save(os.path.join(output_dir, "ts_kappa.npy"),   results["ts_kappa"])
    np.save(os.path.join(output_dir, "ts_L.npy"),       results["ts_L"])
    np.save(os.path.join(output_dir, "ts_dG.npy"),      results["ts_dG"])
    np.save(os.path.join(output_dir, "ts_Phi.npy"),     results["ts_Phi"])
    np.save(os.path.join(output_dir, "ts_mu.npy"),      results["ts_mu"])
    np.save(os.path.join(output_dir, "ts_rho.npy"),     results["ts_rho"])

    # Save final G_econ and C_econ for resolution.py
    np.save(os.path.join(output_dir, "G_econ_final.npy"),
            results["ts_G_econ"][-1])
    np.save(os.path.join(output_dir, "C_econ_final.npy"),
            results["ts_C_econ"][-1])
    np.save(os.path.join(output_dir, "G_legal_final.npy"),
            results["G_legal_final"])

    # Save full C_econ time series (T, n, 3) for monitoring.py
    C_stack = np.stack(results["ts_C_econ"], axis=0)
    np.save(os.path.join(output_dir, "ts_C_econ_full.npy"), C_stack)

    # Save G_legal snapshots: (T, n, n) boolean — records legal scaffold
    # at every timestep so monitoring sees exactly when shock fires
    G_legal_stack = np.stack(results["ts_G_legal"], axis=0)
    np.save(os.path.join(output_dir, "ts_G_legal_full.npy"), G_legal_stack)

    # Save full G_econ time series as 3D array (T, 3n, 3n)
    G_stack = np.stack(results["ts_G_econ"], axis=0)
    np.save(os.path.join(output_dir, "ts_G_econ_full.npy"), G_stack)

    # Save scenario config
    with open(os.path.join(output_dir, "dynamics_meta.json"), "w") as f:
        json.dump({
            "scenario":         results["scenario"],
            "T":                results["T"],
            "n_claims":         results["n_claims"],
            "shock_timestep":   results["shock_timestep"],
            "shock_asset_id":   results["shock_asset_id"],
            "shock_magnitude":  results["shock_magnitude"],
            "cfg":              results["cfg"],
        }, f, indent=2)

    print(f"  Dynamics saved to: {output_dir}/")


# -----------------------------------------------------------------------
# Plot dynamics
# -----------------------------------------------------------------------

def plot_dynamics(results: dict, output_dir: str) -> None:
    """
    Generate dynamics plots showing the co-evolution of all state variables.

    Plot 1: Phi decomposition
        Four-panel plot showing kappa, L, dG_norm, and Phi(t)
        separately so the diagnostic limitation of scalar Phi is visible.
        Paper: Remark — Limitation of Phi as Diagnostic.

    Plot 2: Kernel evolution
        Condition number kappa(t) and rho(t) on one plot showing
        how the interaction kernel deteriorates over time.

    Plot 3: Economic sub-vector evolution
        Mean p, e, l across all claims over time.
        Shows how custody possession degrades and encumbrance grows.
    """
    T        = results["T"]
    scenario = results["scenario"]
    ts       = np.arange(T)
    shock_t  = results["shock_timestep"]
    cfg      = results["cfg"]
    legal_t  = cfg.get("legal_shock_timestep")

    os.makedirs(output_dir, exist_ok=True)

    # ----------------------------------------------------------------
    # Plot 1: Phi decomposition — four panels
    # ----------------------------------------------------------------
    fig = plt.figure(figsize=(14, 10))
    fig.suptitle(
        f"Fragility Observable Decomposition\nScenario: {scenario}",
        fontsize=14, fontweight='bold'
    )

    gs = gridspec.GridSpec(2, 2, hspace=0.45, wspace=0.35)

    # Panel 1: kappa
    ax1 = fig.add_subplot(gs[0, 0])
    ax1.plot(ts, results["ts_kappa"], color="#d62728", lw=1.8)
    ax1.axvline(shock_t, color="gray", ls="--", lw=1, label=f"Shock t={shock_t}")
    if legal_t:
        ax1.axvline(legal_t, color="navy", ls=":", lw=1.5,
                    label=f"Legal shock t={legal_t}")
    ax1.set_title(r"$\kappa(G^{\mathrm{econ}}(t))$ — Coupling Instability",
                  fontsize=10)
    ax1.set_xlabel("Timestep")
    ax1.set_ylabel(r"$\kappa$")
    ax1.legend(fontsize=8)
    ax1.grid(True, alpha=0.3)

    # Panel 2: L(t)
    ax2 = fig.add_subplot(gs[0, 1])
    ax2.plot(ts, results["ts_L"], color="#ff7f0e", lw=1.8)
    ax2.axvline(shock_t, color="gray", ls="--", lw=1)
    if legal_t:
        ax2.axvline(legal_t, color="navy", ls=":", lw=1.5)
    ax2.set_title(r"$L(t) = \sum w_i / V_A$ — Overclaim Ratio", fontsize=10)
    ax2.set_xlabel("Timestep")
    ax2.set_ylabel(r"$L(t)$")
    ax2.grid(True, alpha=0.3)

    # Panel 3: dG norm
    ax3 = fig.add_subplot(gs[1, 0])
    ax3.plot(ts, results["ts_dG"], color="#2ca02c", lw=1.8)
    ax3.axvline(shock_t, color="gray", ls="--", lw=1)
    if legal_t:
        ax3.axvline(legal_t, color="navy", ls=":", lw=1.5)
    ax3.set_title(
        r"$\|dG^{\mathrm{econ}}/dt\|$ — Kernel Velocity", fontsize=10)
    ax3.set_xlabel("Timestep")
    ax3.set_ylabel("Frobenius norm")
    ax3.grid(True, alpha=0.3)

    # Panel 4: Phi
    ax4 = fig.add_subplot(gs[1, 1])
    ax4.plot(ts, results["ts_Phi"], color="#9467bd", lw=2.2)
    ax4.axvline(shock_t, color="gray", ls="--", lw=1, label=f"Shock t={shock_t}")
    if legal_t:
        ax4.axvline(legal_t, color="navy", ls=":", lw=1.5,
                    label=f"Legal shock t={legal_t}")
    ax4.set_title(r"$\Phi(A,t)$ — Aggregate Fragility Observable",
                  fontsize=10)
    ax4.set_xlabel("Timestep")
    ax4.set_ylabel(r"$\Phi$")
    ax4.legend(fontsize=8)
    ax4.grid(True, alpha=0.3)
    ax4.fill_between(ts, results["ts_Phi"], alpha=0.15, color="#9467bd")

    fname1 = os.path.join(output_dir, f"phi_decomposition_{scenario}.png")
    fig.savefig(fname1, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {fname1}")

    # ----------------------------------------------------------------
    # Plot 2: Kernel evolution — kappa and rho on same axes
    # ----------------------------------------------------------------
    fig, ax = plt.subplots(figsize=(12, 5))
    fig.suptitle(
        f"Interaction Kernel Evolution\nScenario: {scenario}",
        fontsize=13, fontweight='bold'
    )

    color_kappa = "#d62728"
    color_rho   = "#1f77b4"

    ax.plot(ts, results["ts_kappa"], color=color_kappa,
            lw=2, label=r"$\kappa(G^{\mathrm{econ}})$ — condition number")
    ax2r = ax.twinx()
    ax2r.plot(ts, results["ts_rho"], color=color_rho,
              lw=2, ls="--", label=r"$\rho(t)$ — mean ancestry overlap")

    ax.axvline(shock_t, color="gray", ls="--", lw=1.2,
               label=f"Collateral shock t={shock_t}")
    if legal_t:
        ax.axvline(legal_t, color="navy", ls=":", lw=1.8,
                   label=f"Legal shock t={legal_t}")

    ax.set_xlabel("Timestep", fontsize=11)
    ax.set_ylabel(r"$\kappa(G^{\mathrm{econ}})$", color=color_kappa, fontsize=11)
    ax2r.set_ylabel(r"$\rho(t)$", color=color_rho, fontsize=11)
    ax.tick_params(axis='y', labelcolor=color_kappa)
    ax2r.tick_params(axis='y', labelcolor=color_rho)

    lines1, labels1 = ax.get_legend_handles_labels()
    lines2, labels2 = ax2r.get_legend_handles_labels()
    ax.legend(lines1 + lines2, labels1 + labels2,
              loc="upper left", fontsize=9)
    ax.grid(True, alpha=0.3)

    fname2 = os.path.join(output_dir, f"kernel_evolution_{scenario}.png")
    fig.savefig(fname2, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {fname2}")

    # ----------------------------------------------------------------
    # Plot 3: Economic sub-vector evolution — mean p, e, l over time
    # ----------------------------------------------------------------
    # Compute mean of each economic dimension across all claims
    mean_p = np.array([C[:, 0].mean() for C in results["ts_C_econ"]])
    mean_e = np.array([C[:, 1].mean() for C in results["ts_C_econ"]])
    mean_l = np.array([C[:, 2].mean() for C in results["ts_C_econ"]])

    fig, ax = plt.subplots(figsize=(12, 5))
    fig.suptitle(
        f"Economic Sub-vector Evolution (Mean Across Claims)\n"
        f"Scenario: {scenario}",
        fontsize=13, fontweight='bold'
    )

    ax.plot(ts, mean_p, color="#1f77b4", lw=2,
            label=r"$\bar{p}(t)$ — custody possession")
    ax.plot(ts, mean_e, color="#d62728", lw=2,
            label=r"$\bar{e}(t)$ — encumbrance level")
    ax.plot(ts, mean_l, color="#2ca02c", lw=2,
            label=r"$\bar{\ell}(t)$ — liquidity/enforcement speed")

    ax.axvline(shock_t, color="gray", ls="--", lw=1.2,
               label=f"Collateral shock t={shock_t}")
    if legal_t:
        ax.axvline(legal_t, color="navy", ls=":", lw=1.8,
                   label=f"Legal shock t={legal_t}")

    ax.set_xlabel("Timestep", fontsize=11)
    ax.set_ylabel("Mean dimension value [0,1]", fontsize=11)
    ax.set_ylim(0, 1.05)
    ax.legend(fontsize=9)
    ax.grid(True, alpha=0.3)
    ax.fill_between(ts, mean_p, mean_e, alpha=0.07, color="#1f77b4")

    fname3 = os.path.join(output_dir, f"econ_evolution_{scenario}.png")
    fig.savefig(fname3, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {fname3}")


# -----------------------------------------------------------------------
# Entry point
# -----------------------------------------------------------------------

if __name__ == "__main__":

    data_base   = "simulation_data"
    output_base = "simulation_results"

    for scenario in ["economic_drift", "legal_shock", "compound"]:
        scenario_dir = os.path.join(data_base, scenario)
        output_dir   = os.path.join(output_base, scenario, "dynamics")

        results = run_dynamics(scenario_dir, output_dir)
        save_dynamics(results, output_dir)
        plot_dynamics(results, output_dir)

    print(f"\n{'='*60}")
    print("Dynamics complete for all three scenarios.")
    print(f"Results saved under: {output_base}/")
    print(f"{'='*60}")
    print("""
Next script:
  monitoring.py -- computes Delta(t), beta(t), tau_intervention
""")
